include:

  # global
  - local: "app/filemetadata/devops/osdu/global/gitlab.yml"

  # containerize
  - local: "app/filemetadata/devops/osdu/containerize/osdu.yml"

  # deploy
  # azure
  - local: "app/filemetadata/devops/osdu/cloud-providers/azure.yml"
