include:

  # aws-global
  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-global.yml"
    ref: release/0.21

  - local: "devops/osdu/cloud-providers/aws-common-pipeline.yml"
